### PR TITLE
Stage 2

### PR DESCRIPTION
**Pull request by bogdan770**
It's first commit of stage-2

### CODE REVIEW

**Comment by bogdan770** [comment]
Done!

**Comment by FiLLa-FaS** [comment]
Hey! thank you for submitting your project. It's already very good! I left several comments below, so you can improve your project and get more scores. Good luck with the refactoring!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * Incorrect distance between `header__link` elements
    * Incorrect distance between all elements in the footer http://joxi.ru/L21glPXcwdBQQr
    * Incorrect width and background color of the `popup__menu` http://joxi.ru/gmvMO4bheODaLr. And also there's incorrect size of the `popup__close_type_menu`. Note, that this menu should contain all screen width and be closed automatically on big screen resolutions http://joxi.ru/J2bdy8DtqpbNvr
    * Incorrect location of the social icons and links in the footer on 320 viewport http://joxi.ru/VrwGn4bso9DL8r
    * You need to round two top corners of the `card`
    * There's no keywords element in the `saved-news` page http://joxi.ru/xAeZEqvHMwKD8r
    * Incorrect background color of the `cards` on `saved-news` page 
    * There should be a space between `cards` and `footer` sections http://joxi.ru/1A5E1PXu4dYl8A
    * There shouldn't be a space between the header bottom line and active underline of the header link http://joxi.ru/vAWEMaLu3wZNem
    * Incorrect text properties of the `savedNews__title`
    * Incorrect spaces between the elements inside `savedNews__container` on 320 viewport
    * Incorrect text properties of the `form__input` (please check the font for this element)
    * Popup doesn't look similar to the mockup on 320 viewport (incorrect width and height
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
    * Please don't use capital letters in the class names (you nedd to check all classes throughout the project
    * You shouldn't use BEM elements or modifiers outside of their block (http://joxi.ru/Y2L14JKcxZz4PA you can see the example on the screenshot). Please check all the project and fix all similar cases
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * You need to use `main` and `section` tags in the project (they should be used in both pages)
    * All text elements should be marked with correct semantic tags http://joxi.ru/LmGO415iB6GPgm
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Popup submit button should have disabled state http://joxi.ru/vAWEMaLu3wZPem
- [ ]  The design reuses components wherever possible.
    * You can use one class for footer links and one class for footer social links http://joxi.ru/D2PNE53cwOyPxr
- [x]  Fonts are connected using `@font-face`.
- [ ]  The icons are exported in SVG format.
    * `notfound` image should be an icon
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
    * One font style doesn't have alternative values http://joxi.ru/4AkXQ48Uj3DpPr
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 71

**Comment by bogdan770** [comment]
I will try Best Practices when i will finish final project, thank you!

**Comment by FiLLa-FaS** [comment]
Hey! Thank you for corrections, you project has been improved. But there're still several issues, please fix them to pass this stage. Good luck with the refactoring!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * Incorrect links width inside the header on 768 viewport http://joxi.ru/V2V0pZdtByo4Wr
    * Burger menu should contain all screen width and be closed automatically on big screen resolutions http://joxi.ru/J2bdy8DtqpbNvr
    * Incorrect font weight of the `saved-news__keywords` http://joxi.ru/eAO8MQRcv3XRYr
    * Incorrect background color of the `cards` on `saved-news` page http://joxi.ru/a2XjDRKHQ8Yzqr http://joxi.ru/nAylQ4bT9JzBZ2
    * There should be a space between `cards` and `footer` sections http://joxi.ru/1A5E1PXu4dYl8A
    * There shouldn't be a space between the header bottom line and active underline of the header link http://joxi.ru/KAgR04Pi5ldyX2
    * Incorrect spaces between the elements inside `savedNews__container` on 320 viewport
    * Popup doesn't look similar to the mockup on 320 viewport (http://joxi.ru/bmoyd40HOZ4GkA http://joxi.ru/V2V0pZdtByolWr)
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
    * You shouldn't use BEM elements or modifiers outside of their block http://joxi.ru/EA401PXtX7ElQA
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * You need to use section tags in the project (they should be used in both pages)
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Popup submit button should have disabled state http://joxi.ru/vAWEMaLu3wZPem
- [ ]  The design reuses components wherever possible.
    * You can use one class for footer links and one class for footer social links http://joxi.ru/D2PNE53cwOyPxr
- [x]  Fonts are connected using `@font-face`.
- [ ]  The icons are exported in SVG format.
    * `notfound` image should be an icon
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 72

**Comment by FiLLa-FaS** [comment]
Hey! Your project is almost finished, only several small issues are left. Note, that the next iteration will be the last. Please check your project before submitting and make sure that most of the comments are fixed. Good luck with refactoring!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * Incorrect background color of the `saved-news` page http://joxi.ru/zAN74gas1RY4Mr
    * Incorrect text properties of the `header__title_saved-news` on 320 viewport
    * Incorrect spaces between the elements inside `header__contaner_saved-news` on 320 viewport http://joxi.ru/YmElYx9TGQpdDr (please check all the spaces)
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
    * You need to use here BEM elements instead of modifiers http://joxi.ru/LmGO415iB6VMZm
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * You need to use `section` tags in the project (they should be used in both pages)
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Popup submit button should have disabled state http://joxi.ru/vAWEMaLu3wZPem
- [ ]  The design reuses components wherever possible.
    * You can use one class for footer links and one class for footer social links http://joxi.ru/D2PNE53cwOyPxr
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
    * `notfound` image should be an icon
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 72

**Comment by bogdan770** [comment]
Thank you for checking me!

**Comment by FiLLa-FaS** [comment]
Hey! You've got more than 80 points, so your project has been accepted. Btw you still can fix several issues below to improve your project. Good luck with the next diploma stage🙌🚀

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Popup submit button should have disabled state http://joxi.ru/vAWEMaLu3wZPem
- [ ]  The design reuses components wherever possible.
    * You can use one class for footer links and one class for footer social links http://joxi.ru/D2PNE53cwOyPxr
- [x]  Fonts are connected using `@font-face`.
- [ ]  The icons are exported in SVG format.
    * `notfound` image should be an icon
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 94

**Pull request merged**
